<?php

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace spec\IPFS\Api;

use IPFS\Api\ApiGenerator;
use PhpParser\BuilderFactory;
use PhpSpec\Exception\Example\NotEqualException;
use PhpSpec\ObjectBehavior;
use Prophecy\Exception\Prediction\FailedPredictionException;

class ApiGeneratorSpec extends ObjectBehavior
{
    public function let()
    {
        $this->beConstructedWith(new BuilderFactory(), sys_get_temp_dir());
    }

    public function it_is_initializable()
    {
        $this->shouldHaveType(ApiGenerator::class);
    }

    public function it_generates_valid_php_code_out_of_api_methods()
    {
        $this->build([
            'foo' => [
                'bar' => [
                    'parts'       => 'foo:bar',
                    'description' => 'foo',
                    'class'       => 'foo',
                    'method'      => 'bar',
                    'arguments'   => [
                        [
                            'name'        => 'foo',
                            'required'    => true,
                            'description' => 'foo argument',
                            'default'     => null,
                            'type'        => 'string',
                        ],
                        [
                            'name'        => 'bar',
                            'required'    => false,
                            'description' => 'bar argument',
                            'default'     => false,
                            'type'        => 'bool',
                        ],
                    ],
                ],
            ],
        ]);

        $code = <<<EOS
<?php

declare (strict_types=1);
namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;
/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class foo implements Api
{
    /**
    * foo
    *
    * @Endpoint(name="foo:bar")
    *
    * @param string \$foo foo argument
    * @param bool \$bar bar argument
    *
    * @return Command
    */
    public function bar(string \$foo, bool \$bar = false) : Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
EOS;
        $file = sys_get_temp_dir() . '/Foo.php';

        if (!file_exists($file)) {
            throw new FailedPredictionException(sprintf('generated Class "%s"is missing', $file));
        }

        if (file_get_contents($file) !== $code) {
            throw new NotEqualException('generated code differs', $code, file_get_contents($file));
        }
    }
}
