<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;
use IPFS\Utils\CaseFormatter;
use PhpParser\Builder\Method;
use PhpParser\BuilderFactory;
use PhpParser\Node;
use PhpParser\PrettyPrinter\Standard;

class ApiGenerator
{
    /**
     * @var BuilderFactory
     */
    private $builder;

    public function __construct(BuilderFactory $builder)
    {
        $this->builder = $builder;
    }

    public function build(array $configs)
    {
        foreach ($configs as $name => $config) {
            $methods = [];

            foreach ($config as $methodConfig) {
                $method = $this->buildMethodNode($methodConfig);

                $methods[] = $method;
            }

            $header = $this->buildHeaderNode();
            $class = $this->buildClassNode($name, $methods);

            $prettyPrinter = new Standard();

            file_put_contents(
                __DIR__ . '/' . ucfirst(CaseFormatter::dashToCamel($name)) . '.php',
                $prettyPrinter->prettyPrintFile([$header, $class])
            );
        }
    }

    private function buildMethodNode(array $methodConfig): Method
    {
        $method = $this->builder
            ->method($methodConfig['method'])
            ->makePublic()
            ->setReturnType('Command')
            ->setDocComment($this->buildDocBlock($methodConfig))
        ;

        foreach ($methodConfig['arguments'] as $parameterConfig) {
            $parameter = $this->builder
                ->param($parameterConfig['name'])
                ->setTypeHint($parameterConfig['type']);

            if (!$parameterConfig['required']) {
                $default = $parameterConfig['default'];

                if ($parameterConfig['type'] === 'int') {
                    $default = (int) $default;
                }
                $parameter->setDefault($default);
            }

            $method->addParam($parameter);
        }

        $method->addStmt(new Node\Stmt\Return_(
            new Node\Expr\New_(new Node\Name('Command'), [
                new Node\Scalar\MagicConst\Method(),
                new Node\Expr\FuncCall(new Node\Name('get_defined_vars')),
            ])
        ));

        return $method;
    }

    private function buildClassNode(string $name, array $methods): Node
    {
        return $this->builder->namespace('IPFS\Api')
            ->addStmt($this->builder->use(Endpoint::class)->as('Endpoint'))
            ->addStmt($this->builder->use(Command::class))
            ->addStmt($this->builder->class($name)
                ->implement('Api')
                ->addStmts($methods)
                ->setDocComment(<<<'EOS'
/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
EOS
                )
                ->makeFinal()
            )
            ->getNode();
    }

    private function buildDocBlock(array $methodConfig): string
    {
        $params = count($methodConfig['arguments']) ? '' : '*';
        $primary = strpos($methodConfig['parts'], ':') === false ? 'true' : 'false';

        foreach ($methodConfig['arguments'] as $index => $argument) {
            $suffix = $index + 1 === count($methodConfig['arguments']) ? "\n*" : "\n";
            $params .= sprintf('* @param %s $%s %s%s', $argument['type'], $argument['name'], $argument['description'], $suffix);
        }

        return <<<EOS
/**
 * {$methodConfig['description']}
 *
 * @Endpoint(primary={$primary}, name="{$methodConfig['parts']}")
 *
 {$params}
 * @return Command
 */
EOS;
    }

    private function buildHeaderNode(): Node
    {
        return new Node\Stmt\Declare_(
            [new Node\Stmt\DeclareDeclare('strict_types', new Node\Scalar\LNumber(1))]
        );
    }
}
