<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Basics implements Api
{
    /**
     * Add a file to ipfs.
     *
     * @Endpoint(primary=true, name="add")
     *
     * @param string $file              the path to a file to be added to IPFS
     * @param bool   $recursive         add directory paths recursively
     * @param bool   $quiet             write minimal output
     * @param bool   $silent            write no output
     * @param bool   $progress          stream progress data
     * @param bool   $trickle           use trickle-dag format for dag generation
     * @param bool   $onlyHash          only chunk and hash - do not write to disk
     * @param bool   $wrapWithDirectory wrap files with a directory object
     * @param bool   $hidden            include files that are hidden
     * @param string $chunker           chunking algorithm to use
     * @param bool   $pin               pin this object when adding
     *
     * @return Command
     */
    public function add(string $file, bool $recursive = false, bool $quiet = false, bool $silent = false, bool $progress = null, bool $trickle = false, bool $onlyHash = false, bool $wrapWithDirectory = false, bool $hidden = false, string $chunker = null, bool $pin = true): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show IPFS object data.
     *
     * @Endpoint(primary=true, name="cat")
     *
     * @param string $arg the path to the IPFS object(s) to be outputted
     *
     * @return Command
     */
    public function cat(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * List all available commands.
     *
     * @Endpoint(primary=true, name="commands")
     *
     * @param bool $flags show command flags
     *
     * @return Command
     */
    public function commands(bool $flags = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * DNS link resolver.
     *
     * @Endpoint(primary=true, name="dns")
     *
     * @param string $arg       the domain-name name to resolve
     * @param bool   $recursive resolve until the result is not a DNS link
     *
     * @return Command
     */
    public function dns(string $arg, bool $recursive = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Download IPFS objects.
     *
     * @Endpoint(primary=true, name="get")
     *
     * @param string $arg              the path to the IPFS object(s) to be outputted
     * @param string $output           the path where the output should be stored
     * @param bool   $archive          output a TAR archive
     * @param bool   $compress         compress the output with GZIP compression
     * @param int    $compressionLevel the level of compression (1-9)
     *
     * @return Command
     */
    public function get(string $arg, string $output = null, bool $archive = false, bool $compress = false, int $compressionLevel = -1): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show IPFS Node ID info.
     *
     * @Endpoint(primary=true, name="id")
     *
     * @param string $arg    peer
     * @param string $format optional output format
     *
     * @return Command
     */
    public function id(string $arg = null, string $format = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * List links from an object.
     *
     * @Endpoint(primary=true, name="ls")
     *
     * @param string $arg         the path to the IPFS object(s) to list links from
     * @param bool   $headers     print table headers (Hash, Size, Name)
     * @param bool   $resolveType resolve linked objects to find out their types
     *
     * @return Command
     */
    public function ls(string $arg, bool $headers = false, bool $resolveType = true): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Mounts IPFS to the filesystem (read-only).
     *
     * @Endpoint(primary=true, name="mount")
     *
     * @param string $ipfsPath the path where IPFS should be mounted
     * @param string $ipnsPath the path where IPNS should be mounted
     *
     * @return Command
     */
    public function mount(string $ipfsPath = null, string $ipnsPath = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Send echo request packets to IPFS hosts.
     *
     * @Endpoint(primary=true, name="ping")
     *
     * @param string $arg   iD of peer to be pinged
     * @param int    $count number of ping messages to send
     *
     * @return Command
     */
    public function ping(string $arg, int $count = 10): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Resolve the value of names to IPFS.
     *
     * @Endpoint(primary=true, name="resolve")
     *
     * @param string $arg       the name to resolve
     * @param bool   $recursive resolve until the result is an IPFS name
     *
     * @return Command
     */
    public function resolve(string $arg, bool $recursive = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * @Endpoint(primary=true, name="update")
     *
     * @param string $arg arguments for subcommand
     *
     * @return Command
     */
    public function update(string $arg = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Shows ipfs version information.
     *
     * @Endpoint(primary=true, name="version")
     *
     * @param bool $number only show the version number
     * @param bool $commit show the commit hash
     * @param bool $repo   show repo version
     * @param bool $all    show all version information
     *
     * @return Command
     */
    public function version(bool $number = false, bool $commit = false, bool $repo = false, bool $all = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
