<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Bitswap implements Api
{
    /**
     * Show the current ledger for a peer.
     *
     * @Endpoint(name="bitswap:ledger")
     *
     * @param string $arg the PeerID (B58) of the ledger to inspect
     *
     * @return Command
     */
    public function ledger(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Trigger reprovider.
     *
     * @Endpoint(name="bitswap:reprovide")
     *
     * @return Command
     */
    public function reprovide(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show some diagnostic information on the bitswap agent.
     *
     * @Endpoint(name="bitswap:stat")
     *
     * @return Command
     */
    public function stat(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Remove a given block from your wantlist.
     *
     * @Endpoint(name="bitswap:unwant")
     *
     * @param string $arg key(s) to remove from your wantlist
     *
     * @return Command
     */
    public function unwant(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show blocks currently on the wantlist.
     *
     * @Endpoint(name="bitswap:wantlist")
     *
     * @param string $peer specify which peer to show wantlist for
     *
     * @return Command
     */
    public function wantlist(string $peer = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
