<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Bitswap implements Api
{
    /**
     * Show some diagnostic information on the bitswap agent.
     *
     * @Endpoint(name="bitswap:stat")
     *
     * @return Command
     */
    public function stat(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Remove a given block from your wantlist.
     *
     * @Endpoint(name="bitswap:unwant")
     *
     * @param string $arg key(s) to remove from your wantlist
     *
     * @return Command
     */
    public function unwant(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show blocks currently on the wantlist.
     *
     * @Endpoint(name="bitswap:wantlist")
     *
     * @param string $peer specify which peer to show wantlist for
     *
     * @return Command
     */
    public function wantlist(string $peer = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
