<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Bootstrap implements Api
{
    /**
     * Add default peers to the bootstrap list.
     *
     * @Endpoint(name="bootstrap:add:default")
     *
     * @return Command
     */
    public function addDefault(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show peers in the bootstrap list.
     *
     * @Endpoint(name="bootstrap:list")
     *
     * @return Command
     */
    public function list(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Remove all peers from the bootstrap list.
     *
     * @Endpoint(name="bootstrap:rm:all")
     *
     * @return Command
     */
    public function rmAll(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
