<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Diag implements Api
{
    /**
     * Clear inactive requests from the log.
     *
     * @Endpoint(primary=false, name="diag:cmds:clear")
     *
     * @return Command
     */
    public function cmdsClear(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Set how long to keep inactive requests in the log.
     *
     * @Endpoint(primary=false, name="diag:cmds:set-time")
     *
     * @param string $arg time to keep inactive requests in log
     *
     * @return Command
     */
    public function cmdsSetTime(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Generates a network diagnostics report.
     *
     * @Endpoint(primary=false, name="diag:net")
     *
     * @param string $vis output format
     *
     * @return Command
     */
    public function net(string $vis = 'text'): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Prints out system diagnostic information.
     *
     * @Endpoint(primary=false, name="diag:sys")
     *
     * @return Command
     */
    public function sys(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
