<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Key implements Api
{
    /**
     * Create a new keypair.
     *
     * @Endpoint(name="key:gen")
     *
     * @param string $arg  name of key to create Required:
     * @param string $type type of the key to create
     * @param int    $size size of the key to generate
     *
     * @return Command
     */
    public function gen(string $arg, string $type = null, int $size = 0): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * List all local keypairs.
     *
     * @Endpoint(name="key:list")
     *
     * @param bool $l show extra information about keys
     *
     * @return Command
     */
    public function list(bool $l = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
