<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Log implements Api
{
    /**
     * Change the logging level.
     *
     * @Endpoint(name="log:level")
     *
     * @param string $arg  the subsystem logging identifier
     * @param string $arg1 the log level, with ‘debug’ the most verbose and ‘critical’ the least verbose
     *
     * @return Command
     */
    public function level(string $arg, string $arg1): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * List the logging subsystems.
     *
     * @Endpoint(name="log:ls")
     *
     * @return Command
     */
    public function ls(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Read the event log.
     *
     * @Endpoint(name="log:tail")
     *
     * @return Command
     */
    public function tail(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
