<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Name implements Api
{
    /**
     * Publish an object to IPNS.
     *
     * @Endpoint(primary=false, name="name:publish")
     *
     * @param string $arg      iPFS path of the object to be published
     * @param bool   $resolve  resolve given path before publishing
     * @param string $lifetime time duration that the record will be valid for
     * @param string $ttl      time duration this record should be cached for (caution: experimental)
     *
     * @return Command
     */
    public function publish(string $arg, bool $resolve = true, string $lifetime = '24h', string $ttl = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Gets the value currently published at an IPNS name.
     *
     * @Endpoint(primary=false, name="name:resolve")
     *
     * @param string $arg       the IPNS name to resolve
     * @param bool   $recursive resolve until the result is not an IPNS name
     * @param bool   $nocache   do not use cached entries
     *
     * @return Command
     */
    public function resolve(string $arg = null, bool $recursive = false, bool $nocache = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
