<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Pin implements Api
{
    /**
     * Pins objects to local storage.
     *
     * @Endpoint(name="pin:add")
     *
     * @param string $arg       path to object(s) to be pinned
     * @param bool   $recursive recursively pin the object linked to by the specified object(s)
     *
     * @return Command
     */
    public function add(string $arg, bool $recursive = true): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * List objects pinned to local storage.
     *
     * @Endpoint(name="pin:ls")
     *
     * @param string $arg   path to object(s) to be listed
     * @param string $type  the type of pinned keys to list
     * @param bool   $quiet write just hashes of objects
     *
     * @return Command
     */
    public function ls(string $arg = null, string $type = 'all', bool $quiet = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Removes the pinned object from local storage.
     *
     * @Endpoint(name="pin:rm")
     *
     * @param string $arg       path to object(s) to be unpinned
     * @param bool   $recursive recursively unpin the object linked to by the specified object(s)
     *
     * @return Command
     */
    public function rm(string $arg, bool $recursive = true): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
