<?php

declare(strict_types=1);

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <https://github.com/digitalkaoz/php-ipfs>
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Repo implements Api
{
    /**
     * Removes repo lockfiles.
     *
     * @Endpoint(name="repo:fsck")
     *
     * @return Command
     */
    public function fsck(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Perform a garbage collection sweep on the repo.
     *
     * @Endpoint(name="repo:gc")
     *
     * @param bool $quiet write minimal output
     *
     * @return Command
     */
    public function gc(bool $quiet = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Get stats for the currently used repo.
     *
     * @Endpoint(name="repo:stat")
     *
     * @param bool $human output RepoSize in MiB
     *
     * @return Command
     */
    public function stat(bool $human = false): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Verify all blocks in repo are not corrupted.
     *
     * @Endpoint(name="repo:verify")
     *
     * @return Command
     */
    public function verify(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show the repo version.
     *
     * @Endpoint(name="repo:version")
     *
     * @param bool $quiet write minimal output
     *
     * @return Command
     */
    public function version(bool $quiet = null): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
