<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Tar implements Api
{
    /**
     * Import a tar file into ipfs.
     *
     * @Endpoint(name="tar:add")
     *
     * @param string $file tar file to add
     *
     * @return Command
     */
    public function add(string $file): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Export a tar file from IPFS.
     *
     * @Endpoint(name="tar:cat")
     *
     * @param string $arg iPFS path of archive to export
     *
     * @return Command
     */
    public function cat(string $arg): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
