<?php

declare(strict_types=1);

/*
 * This file is part of the "php-ipfs" package.
 *
 * (c) Robert Schönthal <robert.schoenthal@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace IPFS\Api;

use IPFS\Annotation\Api as Endpoint;
use IPFS\Command\Command;

/**
 * @author Robert Schönthal <robert.schoenthal@gmail.com>
 * @autogenerated
 * @codeCoverageIgnore
 */
final class Tour implements Api
{
    /**
     * Show a list of IPFS Tour topics.
     *
     * @Endpoint(name="tour:list")
     *
     * @return Command
     */
    public function list(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Show the next IPFS Tour topic.
     *
     * @Endpoint(name="tour:next")
     *
     * @return Command
     */
    public function next(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }

    /**
     * Restart the IPFS Tour.
     *
     * @Endpoint(name="tour:restart")
     *
     * @return Command
     */
    public function restart(): Command
    {
        return new Command(__METHOD__, get_defined_vars());
    }
}
